baseURL = "https://philsimon.github.io/ps-hugo-experiment/"
title = "PS Hugo Experiment"
theme = "beautifulhugo"
DefaultContentLanguage = "en"

[pagination]
  pagerSize = 5

[taxonomies]
  category = "categories"
  tag = "tags"

[Params]
  subtitle = "A Hugo experiment"
  mainSections = ["posts"]
  dateFormat = ":date_long"
  rss = true
  readingTime = true
  colorScheme = "auto"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
